-- Add missing timestamp fields to existing tables
-- These columns were missing from the original schema

ALTER TABLE products ADD COLUMN created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE products ADD COLUMN updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE customers ADD COLUMN created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE customers ADD COLUMN updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sales ADD COLUMN created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE credit_ledger ADD COLUMN created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE staff ADD COLUMN created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE staff ADD COLUMN updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE shifts ADD COLUMN mobile_sales REAL DEFAULT 0 NOT NULL;
